params:
  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: AhaKnow
    subtitle: "凡未知，皆可识📚因知识，而有趣。"
    imageUrl: "Q.gif"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Aha! I Know!
    buttons:
    - name: 💡思辨微光
      url: posts/think
    - name: 🌟识海拾贝
      url: posts/know
    - name: 🚀创业心路
      url: posts/startup

  label: # 左上角图标
    text: "AhaKnow"
    icon: "Q.gif"
    iconHeight: 35

  assets:
    favicon: "Q.gif"
    favicon16x16: "Q.gif"
    favicon32x32: "Q.gif"
    apple_touch_icon: "Q.gif"
    safari_pinned_tab: "Q.gif"
    disableFingerprinting: true # 禁用指纹

  # for search
  fuseOpts:
    isCaseSensitive: false
    includeMatches: true
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
  - identifier: search
    name: 🪄探索
    url: search
    weight: 1
  - identifier: home
    name: 🏡首页
    url: /
    weight: 2
  - identifier: posts
    name: 🚀持续生长
    url: posts
    weight: 3
  - identifier: archives
    name: ⏱️时序长廊
    url: archives
    weight: 4
  - identifier: tags
    name: 🏷️词语标引
    url: tags
    weight: 5
  - identifier: categories
    name: 🖇专题归档
    url: categories
    weight: 5
  - identifier: toolkits
    name: 🧰工具栈
    url: toolkits
    weight: 6
